emc23_sigs_players:
    pattern:  /players
    defaults: { _controller: Emc23SigsBundle:Default:list }

emc23_sigs_player:
     pattern:  /players/{id}
     defaults: { _controller: Emc23SigsBundle:Default:show }

emc23_sigs_buildings:
     pattern:  /buildings
     defaults: { _controller: Emc23SigsBundle:Default:list }

emc23_sigs_building:
     pattern:  /buildings/{id}
     defaults: { _controller: Emc23SigsBundle:Default:show }

emc23_sigs_character:
     pattern:  /characters
     defaults: { _controller: Emc23SigsBundle:Default:list }

emc23_sigs_character:
     pattern:  /characters/{id}
     defaults: { _controller: Emc23SigsBundle:Default:show }

emc23_sigs_hobbits:
     pattern:  /hobbits/
     defaults: { _controller: Emc23SigsBundle:Hobbits:list }

emc23_sigs_hobbit:
     pattern:  /hobbits/{id}/
     defaults: { _controller: Emc23SigsBundle:Hobbits:show }

emc23_sigs_hobbit_types:
    pattern:  /hobbittypes/
    defaults: { _controller: Emc23SigsBundle:HobbitTypes:list }

emc23_sigs_hobbit_type:
        pattern:  /hobbittypes/{id}/
        defaults: { _controller: Emc23SigsBundle:HobbitTypes:show }

emc23_sigs_monsters:
     pattern:  /monsters/
     defaults: { _controller: Emc23SigsBundle:Monsters:list }

emc23_sigs_monster:
     pattern:  /monsters/{id}/
     defaults: { _controller: Emc23SigsBundle:Monsters:show }

emc23_sigs_monster_types:
    pattern:  /monstertypes/
    defaults: { _controller: Emc23SigsBundle:MonsterTypes:list }

emc23_sigs_monster_type:
    pattern:  /monstertypes/{id}/
    defaults: { _controller: Emc23SigsBundle:MonsterTypes:show }