emc23_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: Emc23SigsBundle:Default:index }
    
    
emc23_hello_homepage2:
    pattern:  /addstuff/
    defaults: { _controller: Emc23SigsBundle:Default:add }
    
emc23_hello_homepage3:
    pattern:  /show/{id}/{type}
    defaults: { _controller: Emc23SigsBundle:Default:show }
    
emc23_hello_homepage4:
    pattern:  /showallusers2/
    defaults: { _controller: Emc23SigsBundle:Default:showallusers2 }
    
emc23_hello_homepage5:
    pattern:  /list/{type}
    defaults: { _controller: Emc23SigsBundle:Default:list }
    
emc23_hello_homepage6:
    pattern:  /
    defaults: { _controller: Emc23SigsBundle:Default:index }

emc23_hello_homepage7:
    pattern:  /showfactions
    defaults: { _controller: Emc23SigsBundle:Default:showfactions }
    
emc23_hello_homepage8:
    pattern:  /showgroups
    defaults: { _controller: Emc23SigsBundle:Default:showgroups }
    
emc23_hello_homepage9:
    pattern:  /list/{type}
    defaults: { _controller: Emc23SigsBundle:Default:list }
    
emc23_hello_homepage10:
    pattern:  /new/{type}
    defaults: { _controller: Emc23SigsBundle:Default:new }

emc23_sigs_hobbit_types:
    pattern:  /hobbittypes/
    defaults: { _controller: Emc23SigsBundle:HobbitTypes:list }

emc23_sigs_hobbit_type:
        pattern:  /hobbittypes/{id}/
        defaults: { _controller: Emc23SigsBundle:HobbitTypes:show }

emc23_sigs_hobbits:
    pattern:  /hobbits/
    defaults: { _controller: Emc23SigsBundle:Hobbits:list }

emc23_sigs_hobbit:
        pattern:  /hobbits/{id}/
        defaults: { _controller: Emc23SigsBundle:Hobbits:show }