emc23_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: Emc23HelloBundle:Default:index }
    
    
emc23_hello_homepage2:
    pattern:  /addstuff/
    defaults: { _controller: Emc23HelloBundle:Default:add }
    
emc23_hello_homepage3:
    pattern:  /show/{id}/{type}
    defaults: { _controller: Emc23HelloBundle:Default:show }    
    
emc23_hello_homepage4:
    pattern:  /showallusers2/
    defaults: { _controller: Emc23HelloBundle:Default:showallusers2 }
    
emc23_hello_homepage5:
    pattern:  /list/{type}
    defaults: { _controller: Emc23HelloBundle:Default:list }
    
emc23_hello_homepage6:
    pattern:  /
    defaults: { _controller: Emc23HelloBundle:Default:index }

emc23_hello_homepage7:
    pattern:  /showfactions
    defaults: { _controller: Emc23HelloBundle:Default:showfactions }
    
emc23_hello_homepage8:
    pattern:  /showgroups
    defaults: { _controller: Emc23HelloBundle:Default:showgroups }
    
emc23_hello_homepage9:
    pattern:  /list/{type}
    defaults: { _controller: Emc23HelloBundle:Default:list }
    
emc23_hello_homepage10:
    pattern:  /new/{type}
    defaults: { _controller: Emc23HelloBundle:Default:new }   

